### PR TITLE
Bridge to future docs

### PR DESCRIPTION
**Pull request by drizk1**
So over the summer, I got curious to try using GPT4 to help put together some documentation (which I have since edited) for TidierPlots and then forgot about it until recently. I thought I would share it on the off chance its something you all would like to use as a bridge to more robust docs (which I am sure are coming). If not, please feel free to scrap it, no hard feelings at all.

### CODE REVIEW

**Comment by rdboyes** [comment]
Happy to merge this in as long as it will build! Right now the documenter build seems to be failing though

**Comment by drizk1** [comment]
Sounds good. 

I'll sort out the build issue and get it ready then.

**Comment by drizk1** [comment]
Alright, sorted out the documenter issue (it was mainly not having a space after #s). 

This is definitely not comprehensive (doesnt include things like `ggsave` or `geom_tile` yet to name a few), nor does it fully outline the functionality available for the documented functions, but hopefully it is enough for folks interested in TidierPlots.jl with no ggplot experience to get their plots off the ground.

Happy to incorporate any feedback/thoughts you all might have too

**Comment by drizk1** [comment]
No problem. Just took a scroll thru and there's definitely some rough edges I'll try to come back to and smooth out sooner rather than later (ie putting ; after dropmissing)

**Pull request merged**
